<a href="https://colab.research.google.com/github/Ansh-R-8/Data_Encoding/blob/main/One_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('cars.csv')

In [ ]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['owner'].value_counts()

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64

## OneHotEncoding using pandas

In [ ]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

## K-1 OneHotEncoding

In [ ]:
pd.get_dummies(df, columns = ['fuel', 'owner'], drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

## OneHotEncoding using Sklearn

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[: ,0:4], df.iloc[: ,-1], test_size = 0.2)

In [ ]:
X_train.head()

         brand  km_driven    fuel         owner
1490   Hyundai      50000  Petrol   First Owner
6345    Maruti      20000  Petrol   Third Owner
4329    Toyota      79328  Diesel  Second Owner
5899   Hyundai      50000  Petrol   First Owner
6443  Mahindra     120000  Diesel   First Owner

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first', sparse = False, dtype = np.int32)

In [ ]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [ ]:
X_train_new.shape

(6502, 7)

In [ ]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Hyundai', 50000, 0, ..., 0, 0, 0],
       ['Maruti', 20000, 0, ..., 0, 0, 1],
       ['Toyota', 79328, 1, ..., 1, 0, 0],
       ...,
       ['Honda', 100000, 1, ..., 1, 0, 0],
       ['Honda', 50000, 1, ..., 0, 0, 0],
       ['Maruti', 22000, 0, ..., 0, 0, 0]], dtype=object)

## OneHotEncoding with top Categories

In [ ]:
counts = df['brand'].value_counts()

In [ ]:
df['brand'].nunique()
threshold = 100

32

In [ ]:
repl = counts[counts <= threshold].index

In [ ]:
pd.get_dummies(df['brand'].replace(repl ,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
6479,0,0,0,0,0,0,0,0,0,0,0,0,1
6678,0,0,0,0,0,0,0,1,0,0,0,0,0
1415,0,0,0,0,0,0,0,0,0,0,0,1,0
5920,0,0,0,0,0,0,1,0,0,0,0,0,0
5574,0,0,0,0,0,0,0,1,0,0,0,0,0